// Trạng thái dùng chung giữa các module.
export const state = {
    currentUser: null,
    quizStartTime: 0,
    isQuizRunning: false,
    mode: '',
    currentIdx: 0,
    userAnswers: {},
    timeLeft: 0,
    timerInt: undefined,
    currentExam: [],
    arExamData: [],
    arUserAnswers: {},
    globalStudentList: [],
    importedStudentsCache: [],
    importedQuestionsCache: {},
    practiceTimeLimit: 2700,
    testTimeLimit: 2700,
    maxHintsAllowed: 3,
    hintsUsed: 0,
    unlockedHints: [],
    canCheckCheat: false,
    isProcessingCheat: false,
    wishTimeoutId: null,
    reportImageBase64: "",
    hasSaved: false,
    pendingAuthAction: null,
    currentDeleteId: null
};
